### PR TITLE
Added --not-edited option to query | Added corresponding tests for query and export

### PR DESCRIPTION
**Pull request by oPromessa**
Added --not-edited option to query (exclusive with --edited) to search for photos that have not been edited.

Added query test scenarios for --edited and --not-edited

Added export test scenarios for --edited and --not-edited

### CODE REVIEW

**Comment by oPromessa** [comment]
Local test run successfully, although the automated checks fail on the PR.
```
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.6.2
BuildVersion:	21G320

$ python --version
Python 3.9.6

$ python3 -m pytest -vv 
=========================================== test session starts ============================================
platform darwin -- Python 3.9.6, pytest-7.2.0, pluggy-1.0.0 -- /Users/MSP/Documents/GitHub/osxphotos/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/MSP/Documents/GitHub/osxphotos, configfile: pytest.ini
plugins: mock-3.10.0, cov-4.0.0
collected 1522 items / 1 skipped                                                                           

tests/test_10_12_6.py::test_init PASSED                                                              [  0%]

(...)

tests/test_ventura_dev_preview_13_0_0.py::test_no_adjustments PASSED                                 [ 99%]
tests/test_ventura_dev_preview_13_0_0.py::test_moment[info0] PASSED                                  [100%]

=============== 1413 passed, 110 skipped in 163.66s (0:02:43) ==============
```

**Comment by RhetTbull** [comment]
> Local test run successfully, although the automated checks fail on the PR.

Looks like the test seg-faulted. I've noticed that sometimes happens on the Github actions and I think it's due to some config issue on their end (maybe the worker VM runs out of memory or something). I will re-run the tests.

**Comment by RhetTbull** [comment]
Tests re-ran successfully so must have been an issue with the test runner.

**Comment by RhetTbull** [comment]
Thanks for this! Bonus points for adding tests!  I've merged and will include in the next release.

**Pull request merged**
