### PR TITLE
fix: ignore files without extension as it raises an uncaught error in utitools

### PR DESCRIPTION
**Pull request by dobernhardt**
If a file without an extension (e.g. .DS_Store) is collected during import an uncaught error is raised in utitools as the UTI will be None.
This fix simply ignores all files without extension as it anyhow would not be an image.

### CODE REVIEW

**Comment by RhetTbull** [comment]
Thanks. I actually ran across this today in working a fix for #1757 and implemented a fix which I'll merge shortly. I put the fix in `file_conforms_to_uti()` which will catch this and any other file where UTI cannot be determined (e.g. an invalid extension).

**Comment by RhetTbull** [comment]
@all-contributors please add @dobernhardt for bug

**Comment by dobernhardt** [comment]
> @dobernhardt Please give v0.69.2 a try to see if that fixes the problem. If not, I'll merge your change. Thanks!

0.69.2 works nicely without problems

**Comment by RhetTbull** [comment]
Thanks @dobernhardt for the PR. This issue was fixed separately in v0.69.2.

**Pull request closed without merging**
