### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.

The `ruff` Action uses minimal steps to __run in ~5 seconds__, rapidly providing intuitive GitHub Annotations to contributors.

image

### CODE REVIEW

**Comment by RhetTbull** [comment]
Thanks. I am not currently using a linter on osxphotos so will need to see how much noise ruff makes before I merge this.

**Comment by cclauss** [comment]
Please approve the `1 workflow awaiting approval ` below so we can make sure that it does not make any noise.

**Comment by RhetTbull** [comment]
Which rules are being ignored? 

Also, why did you use 7228 for line length? (I admit, I hate linters that enforce short line lengths. I'm old enough to have used an 80 character phosphorous CRT and I don't understand why modern linters want to continue to enforce that when we're using 4K+ monitors and modern text editors).

**Comment by cclauss** [comment]
I did not pick the number from thin air... I am sure that if we set it to 7227 and rerun the tests some super long line will raise an error.  I am old enough to have used (in anger) 80-column punchcards so I merely set the line length at the limit of the codebase so that if someone comes along and tries to create a new line that is 7229 chars long, they have to justify their excess in a code review.

**Comment by cclauss** [comment]
tests/test_catalina_10_15_7.py:1360:201: E501 Line too long (7228 > 200 characters)

**Comment by RhetTbull** [comment]
That line (7227 chars) and a couple other long ones are test data. Eventually I should add a # noqa to those and use a more reasonable (but still >> 79 chars) line length.

**Comment by RhetTbull** [comment]
@all-contributors please add @cclauss for code

**Pull request merged**
