### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by christiansievers**
tiny typo fix

### CODE REVIEW

**Comment by RhetTbull** [comment]
@christiansievers thanks for this. The README is actually dynamically built as part of the release process. The typo you fixed is in `osxphotos/tutorial.md`. Please update the original in tutorial.md and re-submit the PR otherwise the fix will be overwritten when I next build the README.

**Comment by RhetTbull** [comment]
@all-contributors please add @christiansievers for docs

**Comment by christiansievers** [comment]
I added another commit, now with the correct file edited. Not sure if you can ignore the fix to the dynamically built file.

**Comment by RhetTbull** [comment]
Thanks!

**Pull request merged**
