### PR TITLE
Corrected Panorama Flag

### PR DESCRIPTION
**Pull request by hshore29**
Awesome project! I came across this while working on some custom visualizations of my Photos library, your code was incredibly helpful.

One thing I found is that there are actually two Panorama values - ZKINDSUBTYPE=1 or ZCUSTOMRENDEREDVALUE=6. Some older panoramas (~2013) only had the later value, but I confirmed that the pictures are panos and show up as such in Photos.

So, here's a minor change to set the panorama flag from either condition.

### CODE REVIEW

**Comment by RhetTbull** [comment]
Great--thanks much!  I've not yet had a chance to make the panorama property public in PhotoInfo (next on my list) but glad you found it in the code.  Do you have an example panorama photo of the latter type you'd be willing to share to put in the test library?  If so, you can either share via iCloud to osxphotos.py@gmail.com or email the exported photo to me at the same address

**Comment by hshore29** [comment]
Sure! Here's some more details

In my personal library, I have 16 photos with ZKINDSUBTYPE=1, all of which are definitely panoramas, and all of which have ZCUSTOMRENDEREDVALUE=6. I have another 17 photos with ZCUSTOMRENDEREDVALUE=6, but ZKINDSUBTYPE=0.

I've spot checked a bunch, and they're all panoramas. Attached is one as an example - happy to email it as well if GitHub messes up any of the metadata.
IMG_1403

I'd be interested how the flags are set if you import it - could be an artifact of the Photos upgrade process?

There's another flag I figured out the values for if you're interested in adding it - ZPLAYBACKSTYLE:
```{1: 'still', 2: 'gif', 3: 'live', 4: 'video'}```

**Comment by RhetTbull** [comment]
When I import your test photo, Photos does preserve ZCUSTOMRENDEREDVALUE=6 but does not show the image as panorama (e.g. create a smart folder and filter on photo is panorama).  

Thanks for the info on ZPLAYBACKSTYLE--I'll look at adding those.  This information could likely be inferred from UTI but if there's a use for it, I'm happy to at least pull it into the PhotoInfo._info dict so it's accessible.

**Comment by hshore29** [comment]
I think I figured it out - the "panorama" tag in Photos has two conditions, the first is that it was taken in panorama mode (ZCUSTOMRENDEREDVALUE=6), the second has to do with the proportions of the picture.

I did some tests, and the required proportion is 2.75:1. I had one panorama that was 10342x3734; 2.75 * 3,734 = 10,268.5 so I created two copies, cropped to 10,269  and 10,268. The first one showed up as a panorama but the second one did not. I also double checked and full length vertical panoramas are tagged correctly.

So I guess the two flags have different use cases. If you want to recreate the list of photos in the "Panoramas" folder, you just want ZKINDSUBTYPE=1, but if you want to identify photos taken with the panorama camera (they'll have large / odd dimensions, etc.), you want ZCUSTOMRENDEREDVALUE=6.

**Comment by RhetTbull** [comment]
I looked at my library and the images Photos flags as panorama all have different proportions. My guess is this has to with a change in iOS processing of panoramas and the old ones (pre-change) show up as ZCUSTOMRENDEREDVALUE=6.  I may add a flag for "panorama_type" if anyone has a use case for distinguishing between the two but for now will just leave your change as is to make sure all panoramas are captured.

**Pull request merged**
